{% set version = "0.7.1" %}

package:
  name: prima
  version: {{ version }}

source:
  url: https://github.com/libprima/prima/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 52bc192444b4ebd07c82ef940a01cfe072e8ae2813a84523ec0df55353de7774
  patches:
    - stop.patch  # [win]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('prima', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler("c") }}               # [unix]
    - {{ compiler("fortran") }}         # [unix]
    # flang does not support F2018, use gfortran
    - {{ compiler("m2w64_c") }}         # [win]
    - {{ compiler("m2w64_fortran") }}   # [win]
  run:
    - m2w64-gcc-libgfortran  # [win]

test:
  commands:
    - test -f ${PREFIX}/include/prima/prima.h  # [unix]
    - test -f ${PREFIX}/lib/libprimac${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\include\\prima\\prima.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\libprimac.dll.a exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\libprimac.dll exit 1  # [win]

about:
  home: https://github.com/libprima/prima
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENCE.txt
  summary: package for solving general nonlinear optimization problems without using derivatives

extra:
  recipe-maintainers:
    - jschueller
